ALTER TABLE pos_terminals 
ADD COLUMN IF NOT EXISTS pair_key VARCHAR(20) UNIQUE,
ADD COLUMN IF NOT EXISTS device_type VARCHAR(20) DEFAULT 'pos',
ADD COLUMN IF NOT EXISTS is_master BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS config_data JSONB DEFAULT '{}'::jsonb;
