import pkg from 'pg';
const { Client } = pkg;

const connectionString = 'postgresql://postgres:MJCMYcrORctRbKRtxDTwXjReEcxwNVoe@shortline.proxy.rlwy.net:59800/railway';
const API_BASE = 'http://localhost:3001';

async function runTests() {
  console.log('--- WMS Barcode Parser & Validation Smoke Test ---');

  const client = new Client({ connectionString });
  await client.connect();

  const branch_id = '302bd195-3b79-4f14-a60b-4668c36a12c1'; // Pendik Merkez Depo
  const product_id = 'b0e10001-0000-4000-8000-000000000001'; // Hamburger Ekmeği
  const product_barcode = 'STK-DN-01';
  const target_location_id = '61eda94b-c634-4229-ae00-ea14ae5c595b'; // Zone Z9

  // 1. Insert a temporary WMS task
  console.log('\nInserting temporary warehouse task...');
  const insertRes = await client.query(`
    INSERT INTO warehouse_tasks (
      branch_id,
      task_type,
      status,
      priority,
      description,
      meta
    ) VALUES (
      $1,
      'putaway',
      'pending',
      'normal',
      'Smoke Test Putaway Task',
      $2
    ) RETURNING id
  `, [
    branch_id,
    JSON.stringify({
      product_id,
      barcode: product_barcode,
      product_code: product_barcode,
      product_name: 'Hamburger Ekmeği',
      quantity: 10,
      scanned_quantity: 0,
      source_location: 'Z1',
      target_location: 'Z9',
      target_location_id,
      source_location_id: '61eda94b-c634-4229-ae00-ea14ae5c595b'
    })
  ]);

  const task_id = insertRes.rows[0].id;
  console.log(`Temporary WMS Task created with ID: ${task_id}`);

  try {
    // 2. Test matching product barcode
    console.log('\nTest Case 1: Scanning expected product barcode...');
    const test1 = await fetch(`${API_BASE}/api/wms/parse-barcode`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        barcode: product_barcode,
        branch_id,
        task_id,
        personnel_id: 'TEST-PERSONNEL',
        terminal_id: 'TEST-TERMINAL'
      })
    });
    const res1 = await test1.json();
    console.log('Response:', JSON.stringify(res1, null, 2));
    if (res1.data && res1.data.is_expected && res1.data.scan_type === 'product') {
      console.log('✅ Success: Correct product identified and validated.');
    } else {
      throw new Error('Expected product validation failed.');
    }

    // 3. Test wrong product barcode
    console.log('\nTest Case 2: Scanning unexpected product barcode...');
    const test2 = await fetch(`${API_BASE}/api/wms/parse-barcode`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        barcode: 'WRONG_PRODUCT_BARCODE_123',
        branch_id,
        task_id,
        personnel_id: 'TEST-PERSONNEL',
        terminal_id: 'TEST-TERMINAL'
      })
    });
    const res2 = await test2.json();
    console.log('Response:', JSON.stringify(res2, null, 2));
    if (res2.data && !res2.data.is_expected) {
      console.log('✅ Success: Wrong product correctly rejected by the server.');
    } else {
      throw new Error('Wrong product was not rejected.');
    }

    // 4. Test correct location barcode
    console.log('\nTest Case 3: Scanning expected target location barcode...');
    const test3 = await fetch(`${API_BASE}/api/wms/parse-barcode`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        barcode: 'LOC-Z9-9-9-9', // format generated by loc.zone_code
        branch_id,
        task_id,
        personnel_id: 'TEST-PERSONNEL',
        terminal_id: 'TEST-TERMINAL'
      })
    });
    const res3 = await test3.json();
    console.log('Response:', JSON.stringify(res3, null, 2));
    if (res3.data && res3.data.is_expected && res3.data.scan_type === 'location') {
      console.log('✅ Success: Expected location correctly validated by the server.');
    } else {
      throw new Error('Expected location validation failed.');
    }

    // 5. Test wrong location barcode
    console.log('\nTest Case 4: Scanning incorrect location barcode...');
    const test4 = await fetch(`${API_BASE}/api/wms/parse-barcode`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        barcode: 'LOC-WRONG-SHELF',
        branch_id,
        task_id,
        personnel_id: 'TEST-PERSONNEL',
        terminal_id: 'TEST-TERMINAL'
      })
    });
    const res4 = await test4.json();
    console.log('Response:', JSON.stringify(res4, null, 2));
    if (res4.data && !res4.data.is_expected) {
      console.log('✅ Success: Wrong location correctly rejected by the server.');
    } else {
      throw new Error('Wrong location was not rejected.');
    }

    // 6. Query event logs to ensure success/fail events are written
    console.log('\nFetching logged events in warehouse_task_events for this task...');
    const eventsRes = await client.query(
      'SELECT * FROM warehouse_task_events WHERE task_id = $1 ORDER BY created_at ASC',
      [task_id]
    );
    const events = eventsRes.rows;
    console.log(`Found ${events.length} event logs in database.`);
    events.forEach(event => {
      console.log(`- Event: ${event.event_type} | Barcode: ${event.barcode_scanned} | Payload msg: ${event.payload.message}`);
    });

    if (events.length >= 4) {
      console.log('\n✅ All tests passed. Server verification contract and event logging verified successfully.');
    } else {
      throw new Error('Event logs were not written properly.');
    }
  } finally {
    // 7. Cleanup
    console.log('\nCleaning up database entries...');
    await client.query('DELETE FROM warehouse_task_events WHERE task_id = $1', [task_id]);
    await client.query('DELETE FROM warehouse_tasks WHERE id = $1', [task_id]);
    await client.end();
    console.log('Cleanup complete.');
  }
}

runTests().catch(e => {
  console.error('❌ Test failed with error:', e.message);
  process.exit(1);
});
